# .chr.scl.constants <- tibble::tribble(
#   ~name     , ~value                          , ~description                                       ,
#   "ok"      , "ok"                            , "ok"                                               ,
#   "yesno"   , "yesno"                         , "yesno"                                            ,
#   "int"     , "intercept"                     , "intercept"                                        ,
#   "okx"     , "okcancel"                      , "okcancel"                                         ,
#   "ref"     , "reference"                     , "reference"                                        ,
#   "saf"     , "stringsAsFactors = FALSE"      , "stringsAsFactors = FALSE"                         ,
#   "by"      , " × "                           , "non-escaped padded by operator"                   ,
#   "by0"     , "×"                             , "non-escaped unpadded by operator"                 ,
#   "em"      , " — "                           , "padded em dash"                                   ,
#   "em0"     , "—"                             , "unpadded em dash"                                 ,
#   "en"      , " – "                           , "padded en dash"                                   ,
#   "en0"     , "–"                             , "unpadded en dash"                                 ,
#   "eq"      , " = "                           , "padded equal sign"                                ,
#   "eq0"     , "="                             , "unpadded equal sign"                              ,
#   "or"      , " or "                          , "padded or"                                        ,
#   "or0"     , "or"                            , "unpadded or"                                      ,
#   "pm"      , " ± "                           , "non-escaped padded plus or minus sign"            ,
#   "pm0"     , "±"                             , "non-escaped unpadded plus or minus sign"          ,
#   "and"     , " and "                         , "padded and"                                       ,
#   "and0"    , "and"                           , "unpadded and"                                     ,
#   "ge"      , " ≥ "                           , "non-escaped padded greater than or equal"         ,
#   "ge0"     , "≥"                             , "non-escaped unpadded greater than or equal"       ,
#   "le"      , " ≤ "                           , "non-escaped padded less than or equal"            ,
#   "le0"     , "≤"                             , "non-escaped unpadded less than or equal"          ,
#   "ne"      , " ≠ "                           , "non-escaped padded does not equal"                ,
#   "ne0"     , "≠"                             , "non-escaped unpadded does not equal"              ,
#   "pipe"    , " | "                           , "padded pipe"                                      ,
#   "pipe0"   , "|"                             , "unpadded pipe"                                    ,
#   "plus"    , " + "                           , "padded plus sign"                                 ,
#   "plus0"   , "+"                             , "unpadded plus sign"                               ,
#   "semi"    , "; "                            , "padded semi-colon (followed by space)"            ,
#   "semi0"   , ";"                             , "unpadded semicolon"                               ,
#   "star"    , " * "                           , "padded asterisk"                                  ,
#   "star0"   , "*"                             , "unpadded asterisk"                                ,
#   "colon"   , ": "                            , "padded colon (followed by space)"                 ,
#   "colon0"  , ":"                             , "unpadded colon"                                   ,
#   "comma"   , ", "                            , "padded comma (followed by space)"                 ,
#   "comma0"  , ","                             , "unpadded comma"                                   ,
#   "slash"   , " / "                           , "padded slash"                                     ,
#   "slash0"  , "/"                             , "unpadded slash"                                   ,
#   "tilde"   , " ~ "                           , "padded tilde"                                     ,
#   "tilde0"  , "~"                             , "unpadded tilde"                                   ,
#   "bullet"  , " • "                           , "non-escaped padded bullet"                        ,
#   "bullet0" , "•"                             , "non-escaped unpadded bullet"                      ,
#   "dash"    , " - "                           , "padded dash"                                      ,
#   "dash0"   , "-"                             , "unpadded dash"                                    ,
#   "slashes" , " // "                          , "padded double slash"                              ,
#   "slashes0", "//"                            , "unpadded double slash"                            ,
#   "open"    , "<"                             , "markdown tag open"                                ,
#   "close"   , ">"                             , "markdown tag close"                               ,
#   "quote"   , "'"                             , "single straight quote"                            ,
#   "quote2"  , '\"'                            , "double straight quote"                            ,
#   "lbrace"  , "{"                             , "left curly brace"                                 ,
#   "rbrace"  , "}"                             , "right curly brace"                                ,
#   "lparen"  , "("                             , "left paren"                                       ,
#   "rparen"  , ")"                             , "right paren"                                      ,
#   "lquote"  , "‘"                             , "non-escaped left single quote"                    ,
#   "rquote"  , "‘"                             , "non-escaped right single quote"                   ,
#   "lquote2" , "“"                             , "non-escaped left double quote"                    ,
#   "rquote2" , "”"                             , "non-escaped right double quote"                   ,
#   "lbracket", "["                             , "left square bracket"                              ,
#   "rbracket", "]"                             , "right square bracket"                             ,
#   "inf"     , "\U221E"                        , "unicode infinity"                                 ,
#   "pm"      , " \U00B1 "                      , "unicode padded plus or minus"                     ,
#   "pm0"     , "\U00B1"                        , "unicode unpadded plus or minus"                   ,
#   "le"      , " \U2264 "                      , "unicode padded less than or equal"                ,
#   "le0"     , "\U2264"                        , "unicode unpadded less than or equal"              ,
#   "ge"      , " \U2265 "                      , "unicode padded greater than or equal"             ,
#   "ge0"     , "\U2265"                        , "unicode unpadded greater than or equal"           ,
#   "ne"      , " \U2260 "                      , "unicode padded not equal"                         ,
#   "ne0"     , "\U2260"                        , "unicode unpadded not equal"                       ,
#   "approx"  , " \U2248 "                      , "unicode padded approximately equal"               ,
#   "approx0" , "\U2248"                        , "unicode unpadded approximately equal"             ,
#   "dmd"     , " \U2B29 "                      , "unicode padded diamond"                           ,
#   "dmd0"    , "\U2B29"                        , "unicode unpadded diamond"                         ,
#   "nl"      , "\n"                            , "new line"                                         ,
#   "."       , "."                             , "period"                                           ,
#   "tick"    , "`"                             , "backtick"                                         ,
#   "nbsp"    , " "                             , "non-breaking space"                               ,
#   "blank"   , ""                              , "blank string (0 characters)"                      ,
#   "space"   , " "                             , "space"                                            ,
#   "under"   , "_"                             , "underscore"                                       ,
#   "alpha"   , "\U03B1"                        , "alpha"                                            ,
#   "beta"    , "\U03B2"                        , "beta"                                             ,
#   "gamma"   , "\U03B3"                        , "gamma"                                            ,
#   "delta"   , "\U03B4"                        , "delta"                                            ,
#   "epsilon" , "\U03B5"                        , "epsilon"                                          ,
#   "zeta"    , "\U03B5"                        , "zeta"                                             ,
#   "eta"     , "\U03B7"                        , "eta"                                              ,
#   "theta"   , "\U03B8"                        , "theta"                                            ,
#   "iota"    , "\U03B9"                        , "iota"                                             ,
#   "kappa"   , "\U03BA"                        , "kappa"                                            ,
#   "lambda"  , "\U03BB"                        , "lambda"                                           ,
#   "mu"      , "\U03BC"                        , "mu"                                               ,
#   "nu"      , "\U03BD"                        , "nu"                                               ,
#   "xi"      , "\U03BE"                        , "xi"                                               ,
#   "omicron" , "\U03BF"                        , "omicron"                                          ,
#   "pi"      , "\U03C0"                        , "pi"                                               ,
#   "rho"     , "\U03C1"                        , "rho"                                              ,
#   "sigma"   , "\U03C3"                        , "sigma"                                            ,
#   "tau"     , "\U03C4"                        , "tau"                                              ,
#   "upsilon" , "\U03C5"                        , "upsilon"                                          ,
#   "phi"     , "\U03C6"                        , "phi"                                              ,
#   "chi"     , "\U03C7"                        , "chi"                                              ,
#   "psi"     , "\U03C8"                        , "psi"                                              ,
#   "omega"   , "\U03C9"                        , "omega"                                            ,
#   "ialpha"  , "*\U03B1*"                      , "italic alpha"                                     ,
#   "ibeta"   , "*\U03B2*"                      , "italic beta"                                      ,
#   "igamma"  , "*\U03B3*"                      , "italic gamma"                                     ,
#   "idelta"  , "*\U03B4*"                      , "italic delta"                                     ,
#   "iepsilon", "*\U03B5*"                      , "italic epsilon"                                   ,
#   "izeta"   , "*\U03B5*"                      , "italic zeta"                                      ,
#   "ieta"    , "*\U03B7*"                      , "italic eta"                                       ,
#   "itheta"  , "*\U03B8*"                      , "italic theta"                                     ,
#   "iiota"   , "*\U03B9*"                      , "italic iota"                                      ,
#   "ikappa"  , "*\U03BA*"                      , "italic kappa"                                     ,
#   "ilambda" , "*\U03BB*"                      , "italic lambda"                                    ,
#   "imu"     , "*\U03BC*"                      , "italic mu"                                        ,
#   "inu"     , "*\U03BD*"                      , "italic nu"                                        ,
#   "ixi"     , "*\U03BE*"                      , "italic xi"                                        ,
#   "iomicron", "*\U03BF*"                      , "italic omicron"                                   ,
#   "ipi"     , "*\U03C0*"                      , "italic pi"                                        ,
#   "irho"    , "*\U03C1*"                      , "italic rho"                                       ,
#   "isigma"  , "*\U03C3*"                      , "italic sigma"                                     ,
#   "itau"    , "*\U03C4*"                      , "italic tau"                                       ,
#   "iupsilon", "*\U03C5*"                      , "italic upsilon"                                   ,
#   "iphi"    , "*\U03C6*"                      , "italic phi"                                       ,
#   "ichi"    , "*\U03C7*"                      , "italic chi"                                       ,
#   "ipsi"    , "*\U03C8*"                      , "italic psi"                                       ,
#   "iomega"  , "*\U03C9*"                      , "italic omega"                                     ,
#   "balpha"  , "**\U03B1**"                    , "bold alpha"                                       ,
#   "bbeta"   , "**\U03B2**"                    , "bold beta"                                        ,
#   "bgamma"  , "**\U03B3**"                    , "bold gamma"                                       ,
#   "bdelta"  , "**\U03B4**"                    , "bold delta"                                       ,
#   "bepsilon", "**\U03B5**"                    , "bold epsilon"                                     ,
#   "bzeta"   , "**\U03B5**"                    , "bold zeta"                                        ,
#   "beta"    , "**\U03B7**"                    , "bold eta"                                         ,
#   "btheta"  , "**\U03B8**"                    , "bold theta"                                       ,
#   "biota"   , "**\U03B9**"                    , "bold iota"                                        ,
#   "bkappa"  , "**\U03BA**"                    , "bold kappa"                                       ,
#   "blambda" , "**\U03BB**"                    , "bold lambda"                                      ,
#   "bmu"     , "**\U03BC**"                    , "bold mu"                                          ,
#   "bnu"     , "**\U03BD**"                    , "bold nu"                                          ,
#   "bxi"     , "**\U03BE**"                    , "bold xi"                                          ,
#   "bomicron", "**\U03BF**"                    , "bold omicron"                                     ,
#   "bpi"     , "**\U03C0**"                    , "bold pi"                                          ,
#   "brho"    , "**\U03C1**"                    , "bold rho"                                         ,
#   "bsigma"  , "**\U03C3**"                    , "bold sigma"                                       ,
#   "btau"    , "**\U03C4**"                    , "bold tau"                                         ,
#   "bupsilon", "**\U03C5**"                    , "bold upsilon"                                     ,
#   "bphi"    , "**\U03C6**"                    , "bold phi"                                         ,
#   "bchi"    , "**\U03C7**"                    , "bold chi"                                         ,
#   "bpsi"    , "**\U03C8**"                    , "bold psi"                                         ,
#   "bomega"  , "**\U03C9**"                    , "bold omega"                                       ,
#   "ALPHA"   , "\U0391"                        , "ALPHA"                                            ,
#   "BETA"    , "\U0392"                        , "BETA"                                             ,
#   "GAMMA"   , "\U0393"                        , "GAMMA"                                            ,
#   "DELTA"   , "\U0394"                        , "DELTA"                                            ,
#   "EPSILON" , "\U0395"                        , "EPSILON"                                          ,
#   "ZETA"    , "\U0396"                        , "ZETA"                                             ,
#   "ETA"     , "\U0397"                        , "ETA"                                              ,
#   "THETA"   , "\U0398"                        , "THETA"                                            ,
#   "IOTA"    , "\U0399"                        , "IOTA"                                             ,
#   "KAPPA"   , "\U039A"                        , "KAPPA"                                            ,
#   "LAMBDA"  , "\U039B"                        , "LAMBDA"                                           ,
#   "MU"      , "\U039C"                        , "MU"                                               ,
#   "NU"      , "\U039D"                        , "NU"                                               ,
#   "XI"      , "\U039E"                        , "XI"                                               ,
#   "OMICRON" , "\U039F"                        , "OMICRON"                                          ,
#   "PI"      , "\U03A0"                        , "PI"                                               ,
#   "RHO"     , "\U03A1"                        , "RHO"                                              ,
#   "SIGMA"   , "\U03A3"                        , "SIGMA"                                            ,
#   "TAU"     , "\U03A4"                        , "TAU"                                              ,
#   "UPSILON" , "\U03A5"                        , "UPSILON"                                          ,
#   "PHI"     , "\U03A6"                        , "PHI"                                              ,
#   "CHI"     , "\U03A7"                        , "CHI"                                              ,
#   "PSI"     , "\U03A8"                        , "PSI"                                              ,
#   "OMEGA"   , "\U03A9"                        , "OMEGA"                                            ,
#   "iALPHA"  , "*\U0391*"                      , "italic ALPHA"                                     ,
#   "iBETA"   , "*\U0392*"                      , "italic BETA"                                      ,
#   "iGAMMA"  , "*\U0393*"                      , "italic GAMMA"                                     ,
#   "iDELTA"  , "*\U0394*"                      , "italic DELTA"                                     ,
#   "iEPSILON", "*\U0395*"                      , "italic EPSILON"                                   ,
#   "iZETA"   , "*\U0396*"                      , "italic ZETA"                                      ,
#   "iETA"    , "*\U0397*"                      , "italic ETA"                                       ,
#   "iTHETA"  , "*\U0398*"                      , "italic THETA"                                     ,
#   "iIOTA"   , "*\U0399*"                      , "italic IOTA"                                      ,
#   "iKAPPA"  , "*\U039A*"                      , "italic KAPPA"                                     ,
#   "iLAMBDA" , "*\U039B*"                      , "italic LAMBDA"                                    ,
#   "iMU"     , "*\U039C*"                      , "italic MU"                                        ,
#   "iNU"     , "*\U039D*"                      , "italic NU"                                        ,
#   "iXI"     , "*\U039E*"                      , "italic XI"                                        ,
#   "iOMICRON", "*\U039F*"                      , "italic OMICRON"                                   ,
#   "iPI"     , "*\U03A0*"                      , "italic PI"                                        ,
#   "iRHO"    , "*\U03A1*"                      , "italic RHO"                                       ,
#   "iSIGMA"  , "*\U03A3*"                      , "italic SIGMA"                                     ,
#   "iTAU"    , "*\U03A4*"                      , "italic TAU"                                       ,
#   "iUPSILON", "*\U03A5*"                      , "italic UPSILON"                                   ,
#   "iPHI"    , "*\U03A6*"                      , "italic PHI"                                       ,
#   "iCHI"    , "*\U03A7*"                      , "italic CHI"                                       ,
#   "iPSI"    , "*\U03A8*"                      , "italic PSI"                                       ,
#   "iOMEGA"  , "*\U03A9*"                      , "italic OMEGA"                                     ,
#   "bALPHA"  , "**\U0391**"                    , "bold ALPHA"                                       ,
#   "bBETA"   , "**\U0392**"                    , "bold BETA"                                        ,
#   "bGAMMA"  , "**\U0393**"                    , "bold GAMMA"                                       ,
#   "bDELTA"  , "**\U0394**"                    , "bold DELTA"                                       ,
#   "bEPSILON", "**\U0395**"                    , "bold EPSILON"                                     ,
#   "bZETA"   , "**\U0396**"                    , "bold ZETA"                                        ,
#   "bETA"    , "**\U0397**"                    , "bold ETA"                                         ,
#   "bTHETA"  , "**\U0398**"                    , "bold THETA"                                       ,
#   "bIOTA"   , "**\U0399**"                    , "bold IOTA"                                        ,
#   "bKAPPA"  , "**\U039A**"                    , "bold KAPPA"                                       ,
#   "bLAMBDA" , "**\U039B**"                    , "bold LAMBDA"                                      ,
#   "bMU"     , "**\U039C**"                    , "bold MU"                                          ,
#   "bNU"     , "**\U039D**"                    , "bold NU"                                          ,
#   "bXI"     , "**\U039E**"                    , "bold XI"                                          ,
#   "bOMICRON", "**\U039F**"                    , "bold OMICRON"                                     ,
#   "bPI"     , "**\U03A0**"                    , "bold PI"                                          ,
#   "bRHO"    , "**\U03A1**"                    , "bold RHO"                                         ,
#   "bSIGMA"  , "**\U03A3**"                    , "bold SIGMA"                                       ,
#   "bTAU"    , "**\U03A4**"                    , "bold TAU"                                         ,
#   "bUPSILON", "**\U03A5**"                    , "bold UPSILON"                                     ,
#   "bPHI"    , "**\U03A6**"                    , "bold PHI"                                         ,
#   "bCHI"    , "**\U03A7**"                    , "bold CHI"                                         ,
#   "bPSI"    , "**\U03A8**"                    , "bold PSI"                                         ,
#   "bOMEGA"  , "**\U03A9**"                    , "bold OMEGA"                                       ,
#   "chi2"    , "*\U03C7*<sup>2</sup>"          , "chi squared"                                      ,
#   "brk"     , "<br />"                        , "markdown line break"                              ,
#   "sub1"    , "<sub>"                         , "markdown subscript open"                          ,
#   "sub2"    , "</sub>"                        , "markdown subscript close"                         ,
#   "sup1"    , "<sup>"                         , "markdown superscript open"                        ,
#   "sup2"    , "</sup>"                        , "markdown superscript close"                       ,
#   "b1"      , "<b style=color:'"              , "markdown (bold + color) open"                     ,
#   "b2"      , "</b>"                          , "markdown bold close"                              ,
#   "p1"      , "<span style=color'"            , "markdown (plain + color) open"                    ,
#   "p2"      , "</span>"                       , "markdown plain close"                             ,
#   "c2"      , ">"                             , "markdown generic close"                           ,
#   "blk"     , "#000000FF"                     , "hex black"                                        ,
#   "g10"     , "#1A1A1AFF"                     , "hex 10% grey"                                     ,
#   "g20"     , "#333333FF"                     , "hex 20% grey"                                     ,
#   "g30"     , "#4D4D4DFF"                     , "hex 30% grey"                                     ,
#   "g40"     , "#666666FF"                     , "hex 40% grey"                                     ,
#   "g50"     , "#808080FF"                     , "hex 50% grey"                                     ,
#   "g60"     , "#999999FF"                     , "hex 60% grey"                                     ,
#   "g70"     , "#B3B3B3FF"                     , "hex 70% grey"                                     ,
#   "g80"     , "#CCCCCCFF"                     , "hex 80% grey"                                     ,
#   "g85"     , "#D9D9D9FF"                     , "hex 85% grey"                                     ,
#   "g90"     , "#E6E6E6FF"                     , "hex 90% grey"                                     ,
#   "g95"     , "#F2F2F2FF"                     , "hex 95% grey"                                     ,
#   "wht"     , "#FFFFFFFF"                     , "hex white"                                        ,
#   "inv"     , "#FFFFFF01"                     , "hex invisible (1/256th alpha)"                    ,
#   "blu"     , "#0000AAFF"                     , "hex full blue"                                    ,
#   "cyn"     , "#00FFFFFF"                     , "hex full cyan"                                    ,
#   "grn"     , "#00FF00FF"                     , "hex full green"                                   ,
#   "mag"     , "#FF00FFFF"                     , "hex full magenta"                                 ,
#   "orn"     , "#FF8800FF"                     , "hex full orange"                                  ,
#   "red"     , "#AA0000FF"                     , "hex full red"                                     ,
#   "ylw"     , "#FFFF00FF"                     , "hex full yellow"                                  ,
#   "lblu"    , "#DDDDFFFF"                     , "hex light blue"                                   ,
#   "lcyn"    , "#FFDDFFFF"                     , "hex light cyan"                                   ,
#   "lgrn"    , "#DDFFDDFF"                     , "hex light green"                                  ,
#   "lmag"    , "#FFBBFFFF"                     , "hex light magenta"                                ,
#   "lorn"    , "#FFEEAAFF"                     , "hex light orange"                                 ,
#   "lred"    , "#FFDDDDFF"                     , "hex light red"                                    ,
#   "lylw"    , "#FFFFDDFF"                     , "hex light yellow"                                 ,
#   "mblu"    , "#AAAAFFFF"                     , "hex medium blue"                                  ,
#   "mcyn"    , "#66FFFFFF"                     , "hex medium cyan"                                  ,
#   "mgrn"    , "#FFFF66FF"                     , "hex medium green"                                 ,
#   "mmag"    , "#FF66FFFF"                     , "hex medium magenta"                               ,
#   "morn"    , "#FFAA66FF"                     , "hex medium orange"                                ,
#   "mred"    , "#AFFAAAFF"                     , "hex medium red"                                   ,
#   "mylw"    , "#FFFF66FF"                     , "hex medium yellow"                                ,
#   "dblu"    , "#000080FF"                     , "hex dark blue"                                    ,
#   "dcyn"    , "#008B8BFF"                     , "hex dark cyan"                                    ,
#   "dgrn"    , "#008B00FF"                     , "hex dark green"                                   ,
#   "dmag"    , "#8B008BFF"                     , "hex dark magenta"                                 ,
#   "dorn"    , "#8B4500FF"                     , "hex dark orange"                                  ,
#   "dred"    , "#800000FF"                     , "hex dark red"                                     ,
#   "dylw"    , "#8B8B00FF"                     , "hex dark yellow"                                  ,
#   "bblk"    , "<b style=color:'#000000FF'>"   , "markdown bold hex black open"                     ,
#   "bg10"    , "<b style=color:'#1A1A1AFF'>"   , "markdown bold hex 10% grey open"                  ,
#   "bg20"    , "<b style=color:'#333333FF'>"   , "markdown bold hex 20% grey open"                  ,
#   "bg30"    , "<b style=color:'#4D4D4DFF'>"   , "markdown bold hex 30% grey open"                  ,
#   "bg40"    , "<b style=color:'#666666FF'>"   , "markdown bold hex 40% grey open"                  ,
#   "bg50"    , "<b style=color:'#808080FF'>"   , "markdown bold hex 50% grey open"                  ,
#   "bg60"    , "<b style=color:'#999999FF'>"   , "markdown bold hex 60% grey open"                  ,
#   "bg70"    , "<b style=color:'#B3B3B3FF'>"   , "markdown bold hex 70% grey open"                  ,
#   "bg80"    , "<b style=color:'#CCCCCCFF'>"   , "markdown bold hex 80% grey open"                  ,
#   "bg85"    , "<b style=color:'#D9D9D9FF'>"   , "markdown bold hex 85% grey open"                  ,
#   "bg90"    , "<b style=color:'#E6E6E6FF'>"   , "markdown bold hex 90% grey open"                  ,
#   "bg95"    , "<b style=color:'#F2F2F2FF'>"   , "markdown bold hex 95% grey open"                  ,
#   "bwht"    , "<b style=color:'#FFFFFFFF'>"   , "markdown bold hex white open"                     ,
#   "binv"    , "<b style=color:'#FFFFFF01'>"   , "markdown bold hex invisible (1/256th alpha) open" ,
#   "bblu"    , "<b style=color:'#0000AAFF'>"   , "markdown bold hex full blue open"                 ,
#   "bcyn"    , "<b style=color:'#00FFFFFF'>"   , "markdown bold hex full cyan open"                 ,
#   "bgrn"    , "<b style=color:'#00FF00FF'>"   , "markdown bold hex full green open"                ,
#   "bmag"    , "<b style=color:'#FF00FFFF'>"   , "markdown bold hex full magenta open"              ,
#   "born"    , "<b style=color:'#FF8800FF'>"   , "markdown bold hex full orange open"               ,
#   "bred"    , "<b style=color:'#AA0000FF'>"   , "markdown bold hex full red open"                  ,
#   "bylw"    , "<b style=color:'#FFFF00FF'>"   , "markdown bold hex full yellow open"               ,
#   "blblu"   , "<b style=color:'#DDDDFFFF'>"   , "markdown bold hex light blue open"                ,
#   "blcyn"   , "<b style=color:'#FFDDFFFF'>"   , "markdown bold hex light cyan open"                ,
#   "blgrn"   , "<b style=color:'#DDFFDDFF'>"   , "markdown bold hex light green open"               ,
#   "blmag"   , "<b style=color:'#FFBBFFFF'>"   , "markdown bold hex light magenta open"             ,
#   "blorn"   , "<b style=color:'#FFEEAAFF'>"   , "markdown bold hex light orange open"              ,
#   "blred"   , "<b style=color:'#FFDDDDFF'>"   , "markdown bold hex light red open"                 ,
#   "blylw"   , "<b style=color:'#FFFFDDFF'>"   , "markdown bold hex light yellow open"              ,
#   "bmblu"   , "<b style=color:'#AAAAFFFF'>"   , "markdown bold hex medium blue open"               ,
#   "bmcyn"   , "<b style=color:'#66FFFFFF'>"   , "markdown bold hex medium cyan open"               ,
#   "bmgrn"   , "<b style=color:'#FFFF66FF'>"   , "markdown bold hex medium green open"              ,
#   "bmmag"   , "<b style=color:'#FF66FFFF'>"   , "markdown bold hex medium magenta open"            ,
#   "bmorn"   , "<b style=color:'#FFAA66FF'>"   , "markdown bold hex medium orange open"             ,
#   "bmred"   , "<b style=color:'#AFFAAAFF'>"   , "markdown bold hex medium red open"                ,
#   "bmylw"   , "<b style=color:'#FFFF66FF'>"   , "markdown bold hex medium yellow open"             ,
#   "bdblu"   , "<b style=color:'#000080FF'>"   , "markdown bold hex dark blue open"                 ,
#   "bdcyn"   , "<b style=color:'#008B8BFF'>"   , "markdown bold hex dark cyan open"                 ,
#   "bdgrn"   , "<b style=color:'#008B00FF'>"   , "markdown bold hex dark green open"                ,
#   "bdmag"   , "<b style=color:'#8B008BFF'>"   , "markdown bold hex dark magenta open"              ,
#   "bdorn"   , "<b style=color:'#8B4500FF'>"   , "markdown bold hex dark orange open"               ,
#   "bdred"   , "<b style=color:'#800000FF'>"   , "markdown bold hex dark red open"                  ,
#   "bdylw"   , "<b style=color:'#8B8B00FF'>"   , "markdown bold hex dark yellow open"               ,
#   "pblk"    , "<span style=color:'#000000FF'>", "markdown plain hex black open"                    ,
#   "pg10"    , "<span style=color:'#1A1A1AFF'>", "markdown plain hex 10% grey open"                 ,
#   "pg20"    , "<span style=color:'#333333FF'>", "markdown plain hex 20% grey open"                 ,
#   "pg30"    , "<span style=color:'#4D4D4DFF'>", "markdown plain hex 30% grey open"                 ,
#   "pg40"    , "<span style=color:'#666666FF'>", "markdown plain hex 40% grey open"                 ,
#   "pg50"    , "<span style=color:'#808080FF'>", "markdown plain hex 50% grey open"                 ,
#   "pg60"    , "<span style=color:'#999999FF'>", "markdown plain hex 60% grey open"                 ,
#   "pg70"    , "<span style=color:'#B3B3B3FF'>", "markdown plain hex 70% grey open"                 ,
#   "pg80"    , "<span style=color:'#CCCCCCFF'>", "markdown plain hex 80% grey open"                 ,
#   "pg85"    , "<span style=color:'#D9D9D9FF'>", "markdown plain hex 85% grey open"                 ,
#   "pg90"    , "<span style=color:'#E6E6E6FF'>", "markdown plain hex 90% grey open"                 ,
#   "pg95"    , "<span style=color:'#F2F2F2FF'>", "markdown plain hex 95% grey open"                 ,
#   "pwht"    , "<span style=color:'#FFFFFFFF'>", "markdown plain hex white open"                    ,
#   "pinv"    , "<span style=color:'#FFFFFF01'>", "markdown plain hex invisible (1/256th alpha) open",
#   "pblu"    , "<span style=color:'#0000AAFF'>", "markdown plain hex full blue open"                ,
#   "pcyn"    , "<span style=color:'#00FFFFFF'>", "markdown plain hex full cyan open"                ,
#   "pgrn"    , "<span style=color:'#00FF00FF'>", "markdown plain hex full green open"               ,
#   "pmag"    , "<span style=color:'#FF00FFFF'>", "markdown plain hex full magenta open"             ,
#   "porn"    , "<span style=color:'#FF8800FF'>", "markdown plain hex full orange open"              ,
#   "pred"    , "<span style=color:'#AA0000FF'>", "markdown plain hex full red open"                 ,
#   "pylw"    , "<span style=color:'#FFFF00FF'>", "markdown plain hex full yellow open"              ,
#   "plblu"   , "<span style=color:'#DDDDFFFF'>", "markdown plain hex light blue open"               ,
#   "plcyn"   , "<span style=color:'#FFDDFFFF'>", "markdown plain hex light cyan open"               ,
#   "plgrn"   , "<span style=color:'#DDFFDDFF'>", "markdown plain hex light green open"              ,
#   "plmag"   , "<span style=color:'#FFBBFFFF'>", "markdown plain hex light magenta open"            ,
#   "plorn"   , "<span style=color:'#FFEEAAFF'>", "markdown plain hex light orange open"             ,
#   "plred"   , "<span style=color:'#FFDDDDFF'>", "markdown plain hex light red open"                ,
#   "plylw"   , "<span style=color:'#FFFFDDFF'>", "markdown plain hex light yellow open"             ,
#   "pmblu"   , "<span style=color:'#AAAAFFFF'>", "markdown plain hex medium blue open"              ,
#   "pmcyn"   , "<span style=color:'#66FFFFFF'>", "markdown plain hex medium cyan open"              ,
#   "pmgrn"   , "<span style=color:'#FFFF66FF'>", "markdown plain hex medium green open"             ,
#   "pmmag"   , "<span style=color:'#FF66FFFF'>", "markdown plain hex medium magenta open"           ,
#   "pmorn"   , "<span style=color:'#FFAA66FF'>", "markdown plain hex medium orange open"            ,
#   "pmred"   , "<span style=color:'#AFFAAAFF'>", "markdown plain hex medium red open"               ,
#   "pmylw"   , "<span style=color:'#FFFF66FF'>", "markdown plain hex medium yellow open"            ,
#   "pdblu"   , "<span style=color:'#000080FF'>", "markdown plain hex dark blue open"                ,
#   "pdcyn"   , "<span style=color:'#008B8BFF'>", "markdown plain hex dark cyan open"                ,
#   "pdgrn"   , "<span style=color:'#008B00FF'>", "markdown plain hex dark green open"               ,
#   "pdmag"   , "<span style=color:'#8B008BFF'>", "markdown plain hex dark magenta open"             ,
#   "pdorn"   , "<span style=color:'#8B4500FF'>", "markdown plain hex dark orange open"              ,
#   "pdred"   , "<span style=color:'#800000FF'>", "markdown plain hex dark red open"                 ,
#   "pdylw"   , "<span style=color:'#8B8B00FF'>", "markdown plain hex dark yellow open"
# )
