#' @encoding UTF-8
#' @family values
#' @title Named values (unique to package `uj`)
#' @description Get names, definitions, and values of special `uj` package named values.
#' @details
#' \tabular{ll}{  `value_names, val_names, vnames`   \tab Get names of all package values.                                                                            \cr   \tab   \cr
#'                `value_table, val_table, vtable`   \tab Get a data.frame of all `uj`-specific named values with three columns: `name`, `value`, and `description`,
#'                                                        where named values with multiple elements are pipe-delimited and all values are converted to mode character. \cr   \tab     }
#'                `values, values, vs`                 \tab Get a named list where names are the arguments submitted to `v(...)`, element values are the values of
#'                                                        the contents of the named element, and the attribute `'descriptions'` gives associated verbose descriptions. \cr   \tab   \cr
#' \tabular{ll}{  `value, val, v`                    \tab Gets package values by name.                                                                                                }
#' @param ... Unquoted, comma-separated list of names of values to return. If multiple values are specified, they are coerced into a single atomic vector result.
#' @return **A character vector**         \cr `value_names, val_names, vnames`
#' \cr\cr  **A data.frame**               \cr `value_table, val_table, vtable`
#' \cr\cr  **A \link[=VLS]{vlist}**       \cr `values, values, vs`
#' \cr\cr  **An atomic scalar or vector** \cr `value, val, v`
#' @examples
#' v(.)
#' v(pipe, pipe0, eq)
#' vnames()
#' values()
#' vtable()
#' @export
values <- function() {
  out <- base::list(
    yesno = "yesno",
    okx = "okcancel",
    int = "intercept",
    ref = "reference",
    saf = "stringsAsFactors = FALSE",
    and = "and",
    and1 = " and ",
    back = "\\",
    back1 = " \\ ",
    backs = "\\\\",
    backs1 = " \\\\ ",
    bullet = "\u2022",
    bullet1 = " \u2022 ",
    by = "\u00D7",
    by1 = " \u00D7 ",
    colon = ":",
    colon1 = ": ",
    comma = ",",
    comma1 = ", ",
    dash = "-",
    dash1 = " - ",
    dn = "\u2193",
    dn1 = " \u2193 ",
    em = "—",
    em1 = " — ",
    en0 = "–",
    en1 = " – ",
    eq = "=",
    eq1 = " = ",
    ge = "\u2265",
    ge1 = " \u2265 ",
    le = "\u2264",
    le1 = " \u2264 ",
    lft = "\u2190",
    lft1 = " \u2190 ",
    ne = "\u2260",
    ne1 = " \u2260 ",
    or = "or",
    or1 = " or ",
    pipe = "|",
    pipe1 = " | ",
    plus = "+",
    plus1 = " + ",
    pm = "\u00B1",
    pm1 = " \u00B1 ",
    rgt = "\u2192",
    rgt1 = " \u2192 ",
    semi = ";",
    semi1 = "; ",
    slash = "/",
    slash1 = " / ",
    slashes = "//",
    slashes1 = " // ",
    star = "*",
    star1 = " * ",
    tilde = "~",
    tilde1 = " ~ ",
    up = "\u2191",
    up1 = " \u2191 ",
    open = "<",
    close = ">",
    quote = "'",
    quote2 = "\"",
    lbrace = "{",
    rbrace = "}",
    lparen = "(",
    rparen = ")",
    lquote = "\u2018",
    rquote = "\u2019",
    lquote2 = "\u201C",
    rquote2 = "\u201D",
    lbracket = "[",
    rbracket = "]",
    inf = "\U221E",
    pm = " \U00B1 ",
    pm0 = "\U00B1",
    le = " \U2264 ",
    le0 = "\U2264",
    ge = " \U2265 ",
    ge0 = "\U2265",
    ne = " \U2260",
    ne0 = "\U2260",
    approx = " \U2248 ",
    approx0 = "\U2248",
    dmd = " \U2B29 ",
    dmd0 = "\U2B29",
    nl = "\n",
    . = ".",
    dot = ".",
    tick = "`",
    nbsp = " ",
    blank = "",
    space = " ",
    under = "_",
    alpha = "\U03B1",
    beta = "\U03B2",
    gamma = "\U03B3",
    delta = "\U03B4",
    epsilon = "\U03B5",
    zeta = "\U03B5",
    eta = "\U03B7",
    theta = "\U03B8",
    iota = "\U03B9",
    kappa = "\U03BA",
    lambda = "\U03BB",
    mu = "\U03BC",
    nu = "\U03BD",
    xi = "\U03BE",
    omicron = "\U03BF",
    pi = "\U03C0",
    rho = "\U03C1",
    sigma = "\U03C3",
    tau = "\U03C4",
    upsilon = "\U03C5",
    phi = "\U03C6",
    chi = "\U03C7",
    psi = "\U03C8",
    omega = "\U03C9",
    ialpha = "*\U03B1*",
    ibeta = "*\U03B2*",
    igamma = "*\U03B3*",
    idelta = "*\U03B4*",
    iepsilon = "*\U03B5*",
    izeta = "*\U03B5*",
    ieta = "*\U03B7*",
    itheta = "*\U03B8*",
    iiota = "*\U03B9*",
    ikappa = "*\U03BA*",
    ilambda = "*\U03BB*",
    imu = "*\U03BC*",
    inu = "*\U03BD*",
    ixi = "*\U03BE*",
    iomicron = "*\U03BF*",
    ipi = "*\U03C0*",
    irho = "*\U03C1*",
    isigma = "*\U03C3*",
    itau = "*\U03C4*",
    iupsilon = "*\U03C5*",
    iphi = "*\U03C6*",
    ichi = "*\U03C7*",
    ipsi = "*\U03C8*",
    iomega = "*\U03C9*",
    balpha = "**\U03B1**",
    bbeta = "**\U03B2**",
    bgamma = "**\U03B3**",
    bdelta = "**\U03B4**",
    bepsilon = "**\U03B5**",
    bzeta = "**\U03B5**",
    beta = "**\U03B7**",
    btheta = "**\U03B8**",
    biota = "**\U03B9**",
    bkappa = "**\U03BA**",
    blambda = "**\U03BB**",
    bmu = "**\U03BC**",
    bnu = "**\U03BD**",
    bxi = "**\U03BE**",
    bomicron = "**\U03BF**",
    bpi = "**\U03C0**",
    brho = "**\U03C1**",
    bsigma = "**\U03C3**",
    btau = "**\U03C4**",
    bupsilon = "**\U03C5**",
    bphi = "**\U03C6**",
    bchi = "**\U03C7**",
    bpsi = "**\U03C8**",
    bomega = "**\U03C9**",
    ALPHA = "\U0391",
    BETA = "\U0392",
    GAMMA = "\U0393",
    DELTA = "\U0394",
    EPSILON = "\U0395",
    ZETA = "\U0396",
    ETA = "\U0397",
    THETA = "\U0398",
    IOTA = "\U0399",
    KAPPA = "\U039A",
    LAMBDA = "\U039B",
    MU = "\U039C",
    NU = "\U039D",
    XI = "\U039E",
    OMICRON = "\U039F",
    PI = "\U03A0",
    RHO = "\U03A1",
    SIGMA = "\U03A3",
    TAU = "\U03A4",
    UPSILON = "\U03A5",
    PHI = "\U03A6",
    CHI = "\U03A7",
    PSI = "\U03A8",
    OMEGA = "\U03A9",
    iALPHA = "*\U0391*",
    iBETA = "*\U0392*",
    iGAMMA = "*\U0393*",
    iDELTA = "*\U0394*",
    iEPSILON = "*\U0395*",
    iZETA = "*\U0396*",
    iETA = "*\U0397*",
    iTHETA = "*\U0398*",
    iIOTA = "*\U0399*",
    iKAPPA = "*\U039A*",
    iLAMBDA = "*\U039B*",
    iMU = "*\U039C*",
    iNU = "*\U039D*",
    iXI = "*\U039E*",
    iOMICRON = "*\U039F*",
    iPI = "*\U03A0*",
    iRHO = "*\U03A1*",
    iSIGMA = "*\U03A3*",
    iTAU = "*\U03A4*",
    iUPSILON = "*\U03A5*",
    iPHI = "*\U03A6*",
    iCHI = "*\U03A7*",
    iPSI = "*\U03A8*",
    iOMEGA = "*\U03A9*",
    bALPHA = "**\U0391**",
    bBETA = "**\U0392**",
    bgAMMA = "**\U0393**",
    bDELTA = "**\U0394**",
    bEPSILON = "**\U0395**",
    bZETA = "**\U0396**",
    bETA = "**\U0397**",
    bTHETA = "**\U0398**",
    bIOTA = "**\U0399**",
    bKAPPA = "**\U039A**",
    bLAMBDA = "**\U039B**",
    bMU = "**\U039C**",
    bNU = "**\U039D**",
    bXI = "**\U039E**",
    bOMICRON = "**\U039F**",
    bPI = "**\U03A0**",
    bRHO = "**\U03A1**",
    bSIGMA = "**\U03A3**",
    bTAU = "**\U03A4**",
    bUPSILON = "**\U03A5**",
    bPHI = "**\U03A6**",
    bCHI = "**\U03A7**",
    bPSI = "**\U03A8**",
    bOMEGA = "**\U03A9**",
    chi2  = "*\U03C7*<sup>2</sup>",
    brk   = "<br />",
    sub1  = "<sub>",
    sub2  = "</sub>",
    sup1  = "<sup>",
    sup2  = "</sup>",
    b1    = "<b style=color:'",
    b2    = "</b>",
    p1    = "<span style=color'",
    p2    = "</span>",
    c2    = ">",
    blk   = "#000000FF",
    g10   = "#1A1A1AFF",
    g20   = "#333333FF",
    g30   = "#4D4D4DFF",
    g40   = "#666666FF",
    g50   = "#808080FF",
    g60   = "#999999FF",
    g70   = "#B3B3B3FF",
    g80   = "#ccccccFF",
    g85   = "#D9D9D9FF",
    g90   = "#E6E6E6FF",
    g95   = "#F2F2F2FF",
    wht   = "#FFFFFFFF",
    inv   = "#FFFFFF01",
    blu   = "#0000FFFF",
    cyn   = "#00FFFFFF",
    grn   = "#00FF00FF",
    mag   = "#FF00FFFF",
    orn   = "#FF8800FF",
    red   = "#AA0000FF",
    ylw   = "#FFFF00FF",
    lblu  = "#DDDDFFFF",
    lcyn  = "#FFDDFFFF",
    lgrn  = "#DDFFDDFF",
    lmag  = "#FFBBFFFF",
    lorn  = "#FFEEAAFF",
    lred  = "#FFDDDDFF",
    lylw  = "#FFFFDDFF",
    mblu  = "#AAAAFFFF",
    mcyn  = "#66FFFFFF",
    mgrn  = "#FFFF66FF",
    mmag  = "#FF66FFFF",
    morn  = "#FFAA66FF",
    mred  = "#AFFAAAFF",
    mylw  = "#FFFF66FF",
    dblu  = "#000080FF",
    dcyn  = "#008B8BFF",
    dgrn  = "#008B00FF",
    dmag  = "#8B008BFF",
    dorn  = "#8B4500FF",
    dred  = "#800000FF",
    dylw  = "#8B8B00FF",
    bblk  = "<b style=color:'#000000FF'>",
    bg10  = "<b style=color:'#1A1A1AFF'>",
    bg20  = "<b style=color:'#333333FF'>",
    bg30  = "<b style=color:'#4D4D4DFF'>",
    bg40  = "<b style=color:'#666666FF'>",
    bg50  = "<b style=color:'#808080FF'>",
    bg60  = "<b style=color:'#999999FF'>",
    bg70  = "<b style=color:'#B3B3B3FF'>",
    bg80  = "<b style=color:'#ccccccFF'>",
    bg85  = "<b style=color:'#D9D9D9FF'>",
    bg90  = "<b style=color:'#E6E6E6FF'>",
    bg95  = "<b style=color:'#F2F2F2FF'>",
    bwht  = "<b style=color:'#FFFFFFFF'>",
    binv  = "<b style=color:'#FFFFFF01'>",
    bblu  = "<b style=color:'#0000FFFF'>",
    bcyn  = "<b style=color:'#00FFFFFF'>",
    bgrn  = "<b style=color:'#00FF00FF'>",
    bmag  = "<b style=color:'#FF00FFFF'>",
    born  = "<b style=color:'#FF8800FF'>",
    bred  = "<b style=color:'#AA0000FF'>",
    bylw  = "<b style=color:'#FFFF00FF'>",
    blblu = "<b style=color:'#DDDDFFFF'>",
    blcyn = "<b style=color:'#FFDDFFFF'>",
    blgrn = "<b style=color:'#DDFFDDFF'>",
    blmag = "<b style=color:'#FFBBFFFF'>",
    blorn = "<b style=color:'#FFEEAAFF'>",
    blred = "<b style=color:'#FFDDDDFF'>",
    blylw = "<b style=color:'#FFFFDDFF'>",
    bmblu = "<b style=color:'#AAAAFFFF'>",
    bmcyn = "<b style=color:'#66FFFFFF'>",
    bmgrn = "<b style=color:'#FFFF66FF'>",
    bmmag = "<b style=color:'#FF66FFFF'>",
    bmorn = "<b style=color:'#FFAA66FF'>",
    bmred = "<b style=color:'#AFFAAAFF'>",
    bmylw = "<b style=color:'#FFFF66FF'>",
    bdblu = "<b style=color:'#000080FF'>",
    bdcyn = "<b style=color:'#008B8BFF'>",
    bdgrn = "<b style=color:'#008B00FF'>",
    bdmag = "<b style=color:'#8B008BFF'>",
    bdorn = "<b style=color:'#8B4500FF'>",
    bdred = "<b style=color:'#800000FF'>",
    bdylw = "<b style=color:'#8B8B00FF'>",
    pblk  = "<span style=color:'#000000FF'>",
    pg10  = "<span style=color:'#1A1A1AFF'>",
    pg20  = "<span style=color:'#333333FF'>",
    pg30  = "<span style=color:'#4D4D4DFF'>",
    pg40  = "<span style=color:'#666666FF'>",
    pg50  = "<span style=color:'#808080FF'>",
    pg60  = "<span style=color:'#999999FF'>",
    pg70  = "<span style=color:'#B3B3B3FF'>",
    pg80  = "<span style=color:'#ccccccFF'>",
    pg85  = "<span style=color:'#D9D9D9FF'>",
    pg90  = "<span style=color:'#E6E6E6FF'>",
    pg95  = "<span style=color:'#F2F2F2FF'>",
    pwht  = "<span style=color:'#FFFFFFFF'>",
    pinv  = "<span style=color:'#FFFFFF01'>",
    pblu  = "<span style=color:'#0000AAFF'>",
    pcyn  = "<span style=color:'#00FFFFFF'>",
    pgrn  = "<span style=color:'#00FF00FF'>",
    pmag  = "<span style=color:'#FF00FFFF'>",
    porn  = "<span style=color:'#FF8800FF'>",
    pred  = "<span style=color:'#AA0000FF'>",
    pylw  = "<span style=color:'#FFFF00FF'>",
    plblu   = "<span style=color:'#DDDDFFFF'>",
    plcyn   = "<span style=color:'#FFDDFFFF'>",
    plgrn   = "<span style=color:'#DDFFDDFF'>",
    plmag   = "<span style=color:'#FFBBFFFF'>",
    plorn   = "<span style=color:'#FFEEAAFF'>",
    plred   = "<span style=color:'#FFDDDDFF'>",
    plylw   = "<span style=color:'#FFFFDDFF'>",
    pmblu   = "<span style=color:'#AAAAFFFF'>",
    pmcyn   = "<span style=color:'#66FFFFFF'>",
    pmgrn   = "<span style=color:'#FFFF66FF'>",
    pmmag   = "<span style=color:'#FF66FFFF'>",
    pmorn   = "<span style=color:'#FFAA66FF'>",
    pmred   = "<span style=color:'#AFFAAAFF'>",
    pmylw   = "<span style=color:'#FFFF66FF'>",
    pdblu   = "<span style=color:'#000080FF'>",
    pdcyn   = "<span style=color:'#008B8BFF'>",
    pdgrn   = "<span style=color:'#008B00FF'>",
    pdmag   = "<span style=color:'#8B008BFF'>",
    pdorn   = "<span style=color:'#8B4500FF'>",
    pdred   = "<span style=color:'#800000FF'>",
    pdylw   = "<span style=color:'#8B8B00FF'>",
    pt      = ggplot2::.pt,
    NAL     = NA,
    NAR     = NA_real_,
    NAI     = NA_integer_,
    NAC     = NA_character_,
    one     = 0.99999999,
    zero    = 0.00000001,
    colors  = base::c('#600000FF', '#000060FF', '#6B006BFF', '#303030FF', '#6B3500FF', '#FF0000FF', '#0000FFFF', '#FF00FFFF', '#606060FF', '#FF8800FF'),
    lines   = base::c('solid', '42', '22', '11', '4111', '2111', '1114', '1112', '1441'),
    edots   = base::c(5, 0, 2, 6, 1),
    fdots   = base::c(21, 23, 24, 22, 25),
    ldots   = base::c(4, 8, 35, 36, 37, 38, 42, 43, 45, 47, 60, 61, 62, 64, 92, 94, 124, 126),
    ndots   = uj::asCHR(0:9),
    pdots   = base::c("!", "@", "#", "$", "%", "&", "?"),
    sdots   = base::c(16, 18, 17, 15),
    azdots  = letters,
    AZdots  = LETTERS,
    digits  = uj::asCHR(0:9),
    az      = letters,
    AZ      = LETTERS,
    azAZ    = base::c(letters, LETTERS),
    vowels  = base::c('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'),
    files   = base::c(letters, LETTERS, 0:9, '(', ')', '_', '.', ' ', ',', '-'),
    models  = base::c(letters, LETTERS, 0:9, ' ', '+', '*', '~', ':', '_', '.'),
    labels  = base::c(letters, LETTERS, 0:9, '(', ')', '[', '_', ']', '{', '}', '.', ' ', ',', '-'),
    names   = base::c(letters, LETTERS, 0:9, '_', '.'),
    right   = base::c(letters, LETTERS, 0:9, ' ', '+' ,'*', ':', '_', '.'),
    files0  = base::c(letters, LETTERS, 0:9, '(', ')', '.', ' ', ',', '-'),
    names0  = base::c(letters, LETTERS, 0:9, '.'),
    models0 = base::c(letters, LETTERS, 0:9, ' ', '+', '*', '~'),
    right0  = base::c(letters, LETTERS, 0:9, ' ', '+', '*'),
    bbb = uj:::.bbb,
    ccc = uj:::.ccc,
    ddd = uj:::.ddd,
    eee = uj:::.eee,
    iii = uj:::.iii,
    mmm = uj:::.mmm,
    sss = uj:::.sss,
    BBB = uj:::.BBB,
    CCC = uj:::.CCC,
    DDD = uj:::.DDD,
    EEE = uj:::.EEE,
    III = uj:::.III,
    MMM = uj:::.MMM,
    SSS = uj:::.SSS
  )
  descriptions <- base::c(
    yesno = "yes/no spec for dialog box buttons in ?dialogs functions",
    okx = "ok/cancel spec for dialog box buttons in ?dialogs functions",
    int = "intercept",
    ref = "reference",
    saf = "'stringsAsFactors = FALSE' argument for data.frame calls",
    and = "and",
    and1 = "padded and",
    back = "backslash",
    back1 = "padded backslash",
    backs = "double backslash",
    backs1 = "padded double backslash",
    bullet = "bullet",
    bullet1 = "padded bullet",
    by = "by operator",
    by1 = "padded 'by' operator",
    colon = "colon",
    colon1 = "padded colon (followed by space)",
    comma = "comma",
    comma1 = "padded comma (followed by space)",
    dash = "unpadded dash",
    dash1 = "padded dash",
    dn = "down arrow",
    dn1 = "padded down arrow",
    em = "em dash",
    em1 = "padded em dash",
    en0 = "en dash",
    en1 = "padded en dash",
    eq = "equals operator",
    eq1 = "padded equal sign",
    ge = "greater than or equal operator",
    ge1 = "padded greater than or equal",
    le = "less than or equal operator",
    le1 = "padded less than or equal",
    lft = "left arrow",
    lft1 = "padded left arrow",
    ne = "does not equal operator",
    ne1 = "padded does not equal",
    or = "or",
    or1 = "padded or",
    pipe = "pipe",
    pipe1 = "padded pipe",
    plus = "plus operator",
    plus1 = "padded plus operator",
    pm = "plus or minus operator",
    pm1 = "padded plus or minus sign",
    rgt = "right arrow",
    rgt1 = "padded right arrow",
    semi = "semicolon",
    semi1 = "padded semi-colon (followed by space)",
    slash = "slash",
    slash1 = "padded slash",
    slashes = "unpadded double slash",
    slashes1 = "padded double slash",
    star = "asterisk",
    star1 = "padded asterisk",
    tilde = "tilde",
    tilde1 = "padded tilde",
    up = "up arrow",
    up1 = "padded up arrow",
    open = "markdown tag open",
    close = "markdown tag close",
    quote = "single straight quote",
    quote2 = "double straight quote",
    lbrace = "left curly brace",
    rbrace = "right curly brace",
    lparen = "left paren",
    rparen = "right paren",
    lquote = "left single quote",
    rquote = "non-escaped right single quote",
    lquote2 = "non-escaped left double quote",
    rquote2 = "non-escaped right double quote",
    lbracket = "left square bracket",
    rbracket = "right square bracket",
    inf = "unicode infinity",
    pm = "unicode padded plus or minus",
    pm0 = "unicode unpadded plus or minus",
    le = "unicode padded less than or equal",
    le0 = "unicode unpadded less than or equal",
    ge = "unicode padded greater than or equal",
    ge0 = "unicode unpadded greater than or equal",
    ne = " unicode padded not equal",
    ne0 = "unicode unpadded not equal",
    approx = "unicode padded approximately equal",
    approx0 = "unicode unpadded approximately equal",
    dmd = "unicode padded diamond",
    dmd0 = "unicode unpadded diamond",
    nl = "new line",
    . = "period",
    dot = "period",
    tick = "backtick",
    nbsp = "non-breaking space",
    blank = "blank string (0 characters)",
    space = "space",
    under = "underscore",
    alpha = "alpha",
    beta = "beta",
    gamma = "gamma",
    delta = "delta",
    epsilon = "epsilon",
    zeta = "zeta",
    eta = "eta",
    theta = "theta",
    iota = "iota",
    kappa = "kappa",
    lambda = "lambda",
    mu = "mu",
    nu = "nu",
    xi = "xi",
    omicron = "omicron",
    pi = "pi",
    rho = "rho",
    sigma = "sigma",
    tau = "tau",
    upsilon = "upsilon",
    phi = "phi",
    chi = "chi",
    psi = "psi",
    omega = "omega",
    ialpha = "italic alpha",
    ibeta = "italic beta",
    igamma = "italic gamma",
    idelta = "italic delta",
    iepsilon = "italic epsilon",
    izeta = "italic zeta",
    ieta = "italic eta",
    itheta = "italic theta",
    iiota = "italic iota",
    ikappa = "italic kappa",
    ilambda = "italic lambda",
    imu = "italic mu",
    inu = "italic nu",
    ixi = "italic xi",
    iomicron = "italic omicron",
    ipi = "italic pi",
    irho = "italic rho",
    isigma = "italic sigma",
    itau = "italic tau",
    iupsilon = "italic upsilon",
    iphi = "italic phi",
    ichi = "italic chi",
    ipsi = "italic psi",
    iomega = "italic omega",
    balpha = "bold alpha",
    bbeta = "bold beta",
    bgamma = "bold gamma",
    bdelta = "bold delta",
    bepsilon = "bold epsilon",
    bzeta = "bold zeta",
    beta = "bold eta",
    btheta = "bold theta",
    biota = "bold iota",
    bkappa = "bold kappa",
    blambda = "bold lambda",
    bmu = "bold mu",
    bnu = "bold nu",
    bxi = "bold xi",
    bomicron = "bold omicron",
    bpi = "bold pi",
    brho = "bold rho",
    bsigma = "bold sigma",
    btau = "bold tau",
    bupsilon = "bold upsilon",
    bphi = "bold phi",
    bchi = "bold chi",
    bpsi = "bold psi",
    bomega = "bold omega",
    ALPHA = "ALPHA",
    BETA = "BETA",
    GAMMA = "GAMMA",
    DELTA = "DELTA",
    EPSILON = "EPSILON",
    ZETA = "ZETA",
    ETA = "ETA",
    THETA = "THETA",
    IOTA = "IOTA",
    KAPPA = "KAPPA",
    LAMBDA = "LAMBDA",
    MU = "MU",
    NU = "NU",
    XI = "XI",
    OMICRON = "OMICRON",
    PI = "PI",
    RHO = "RHO",
    SIGMA = "SIGMA",
    TAU = "TAU",
    UPSILON = "UPSILON",
    PHI = "PHI",
    CHI = "CHI",
    PSI = "PSI",
    OMEGA = "OMEGA",
    iALPHA = "italic ALPHA",
    iBETA = "italic BETA",
    iGAMMA = "italic GAMMA",
    iDELTA = "italic DELTA",
    iEPSILON = "italic EPSILON",
    iZETA = "italic ZETA",
    iETA = "italic ETA",
    iTHETA = "italic THETA",
    iIOTA = "italic IOTA",
    iKAPPA = "italic KAPPA",
    iLAMBDA = "italic LAMBDA",
    iMU = "italic MU",
    iNU = "italic NU",
    iXI = "italic XI",
    iOMICRON = "italic OMICRON",
    iPI = "italic PI",
    iRHO = "italic RHO",
    iSIGMA = "italic SIGMA",
    iTAU = "italic TAU",
    iUPSILON = "italic UPSILON",
    iPHI = "italic PHI",
    iCHI = "italic CHI",
    iPSI = "italic PSI",
    iOMEGA = "italic OMEGA",
    bALPHA = "bold ALPHA",
    bBETA = "bold BETA",
    bgAMMA = "bold GAMMA",
    bDELTA = "bold DELTA",
    bEPSILON = "bold EPSILON",
    bZETA = "bold ZETA",
    bETA = "bold ETA",
    bTHETA = "bold THETA",
    bIOTA = "bold IOTA",
    bKAPPA = "bold KAPPA",
    bLAMBDA = "bold LAMBDA",
    bMU = "bold MU",
    bNU = "bold NU",
    bXI = "bold XI",
    bOMICRON = "bold OMICRON",
    bPI = "bold PI",
    bRHO = "bold RHO",
    bSIGMA = "bold SIGMA",
    bTAU = "bold TAU",
    bUPSILON = "bold UPSILON",
    bPHI = "bold PHI",
    bCHI = "bold CHI",
    bPSI = "bold PSI",
    bOMEGA = "bold OMEGA",
    chi2 = "chi squared",
    brk = "markdown line break",
    sub1 = "markdown subscript open",
    sub2 = "markdown subscript close",
    sup1 = "markdown superscript open",
    sup2 = "markdown superscript close",
    b1 = "markdown (bold + color) open",
    b2 = "markdown bold close",
    p1 = "markdown (plain + color) open",
    p2 = "markdown plain close",
    c2 = "markdown generic close",
    blk = "hex black",
    g10 = "hex 10% grey",
    g20 = "hex 20% grey",
    g30 = "hex 30% grey",
    g40 = "hex 40% grey",
    g50 = "hex 50% grey",
    g60 = "hex 60% grey",
    g70 = "hex 70% grey",
    g80 = "hex 80% grey",
    g85 = "hex 85% grey",
    g90 = "hex 90% grey",
    g95 = "hex 95% grey",
    wht = "hex white",
    inv = "hex invisible (1/256th alpha)",
    blu = "hex full blue",
    cyn = "hex full cyan",
    grn = "hex full green",
    mag = "hex full magenta",
    orn = "hex full orange",
    red = "hex full red",
    ylw = "hex full yellow",
    lblu = "hex light blue",
    lcyn = "hex light cyan",
    lgrn = "hex light green",
    lmag = "hex light magenta",
    lorn = "hex light orange",
    lred = "hex light red",
    lylw = "hex light yellow",
    mblu = "hex medium blue",
    mcyn = "hex medium cyan",
    mgrn = "hex medium green",
    mmag = "hex medium magenta",
    morn = "hex medium orange",
    mred = "hex medium red",
    mylw = "hex medium yellow",
    dblu = "hex dark blue",
    dcyn = "hex dark cyan",
    dgrn = "hex dark green",
    dmag = "hex dark magenta",
    dorn = "hex dark orange",
    dred = "hex dark red",
    dylw = "hex dark yellow",
    bblk = "markdown bold hex black open",
    bg10 = "markdown bold hex 10% grey open",
    bg20 = "markdown bold hex 20% grey open",
    bg30 = "markdown bold hex 30% grey open",
    bg40 = "markdown bold hex 40% grey open",
    bg50 = "markdown bold hex 50% grey open",
    bg60 = "markdown bold hex 60% grey open",
    bg70 = "markdown bold hex 70% grey open",
    bg80 = "markdown bold hex 80% grey open",
    bg85 = "markdown bold hex 85% grey open",
    bg90 = "markdown bold hex 90% grey open",
    bg95 = "markdown bold hex 95% grey open",
    bwht = "markdown bold hex white open",
    binv = "markdown bold hex invisible (1/256th alpha) open",
    bblu = "markdown bold hex full blue open",
    bcyn = "markdown bold hex full cyan open",
    bgrn = "markdown bold hex full green open",
    bmag = "markdown bold hex full magenta open",
    born = "markdown bold hex full orange open",
    bred = "markdown bold hex full red open",
    bylw = "markdown bold hex full yellow open",
    blblu = "markdown bold hex light blue open",
    blcyn = "markdown bold hex light cyan open",
    blgrn = "markdown bold hex light green open",
    blmag = "markdown bold hex light magenta open",
    blorn = "markdown bold hex light orange open",
    blred = "markdown bold hex light red open",
    blylw = "markdown bold hex light yellow open",
    bmblu = "markdown bold hex medium blue open",
    bmcyn = "markdown bold hex medium cyan open",
    bmgrn = "markdown bold hex medium green open",
    bmmag = "markdown bold hex medium magenta open",
    bmorn = "markdown bold hex medium orange open",
    bmred = "markdown bold hex medium red open",
    bmylw = "markdown bold hex medium yellow open",
    bdblu = "markdown bold hex dark blue open",
    bdcyn = "markdown bold hex dark cyan open",
    bdgrn = "markdown bold hex dark green open",
    bdmag = "markdown bold hex dark magenta open",
    bdorn = "markdown bold hex dark orange open",
    bdred = "markdown bold hex dark red open",
    bdylw = "markdown bold hex dark yellow open",
    pblk = "markdown plain hex black open",
    pg10 = "markdown plain hex 10% grey open",
    pg20 = "markdown plain hex 20% grey open",
    pg30 = "markdown plain hex 30% grey open",
    pg40 = "markdown plain hex 40% grey open",
    pg50 = "markdown plain hex 50% grey open",
    pg60 = "markdown plain hex 60% grey open",
    pg70 = "markdown plain hex 70% grey open",
    pg80 = "markdown plain hex 80% grey open",
    pg85 = "markdown plain hex 85% grey open",
    pg90 = "markdown plain hex 90% grey open",
    pg95 = "markdown plain hex 95% grey open",
    pwht = "markdown plain hex white open",
    pinv = "markdown plain hex invisible (1/256th alpha) open",
    pblu = "markdown plain hex full blue open",
    pcyn = "markdown plain hex full cyan open",
    pgrn = "markdown plain hex full green open",
    pmag = "markdown plain hex full magenta open",
    porn = "markdown plain hex full orange open",
    pred = "markdown plain hex full red open",
    pylw = "markdown plain hex full yellow open",
    plblu = "markdown plain hex light blue open",
    plcyn = "markdown plain hex light cyan open",
    plgrn = "markdown plain hex light green open",
    plmag = "markdown plain hex light magenta open",
    plorn = "markdown plain hex light orange open",
    plred = "markdown plain hex light red open",
    plylw = "markdown plain hex light yellow open",
    pmblu = "markdown plain hex medium blue open",
    pmcyn = "markdown plain hex medium cyan open",
    pmgrn = "markdown plain hex medium green open",
    pmmag = "markdown plain hex medium magenta open",
    pmorn = "markdown plain hex medium orange open",
    pmred = "markdown plain hex medium red open",
    pmylw = "markdown plain hex medium yellow open",
    pdblu = "markdown plain hex dark blue open",
    pdcyn = "markdown plain hex dark cyan open",
    pdgrn = "markdown plain hex dark green open",
    pdmag = "markdown plain hex dark magenta open",
    pdorn = "markdown plain hex dark orange open",
    pdred = "markdown plain hex dark red open",
    pdylw = "markdown plain hex dark yellow open",
    pt = "the size of a single point (a ggplot constant)",
    NAL = "logical NA",
    NAR = "real valued NA",
    NAI = "integer NA",
    NAC = "character NA",
    one = "almost one",
    zero = "almost zero",
    colors = "plot palette: colors >> { dark.red, dark.blue, dark.magenta, black, dark.orange, full.red, full.blue, full.magenta, grey40, full.orange }",
    lines  = "plot palette: line.types >> { solid 42 22 11 4111, 2111 1114 1112 1441 }",
    edots  = "plot palette: empty.dots >> { circle, up.triangle, down.triangle, diamond, square }",
    fdots  = "plot palette: fill.dots  >> { circle, up.triangle, down.triangle, diamond, square } ",
    ldots  = "plot palette: line.dots  >> { × + < > ^ v ~ | / — \\ }",
    ndots  = "plot palette: digit.dots >> { 0 1 2 3 4 5 6 7 8 9 }",
    pdots  = "plot palette: punc.dots  >> { ! @ # $ % & ? }",
    sdots  = "plot palette: solid.dots >> { circle, up.triangle, square, diamond }",
    azdots = "plot palette: az.dots >> { a b c d e f g ... z }",
    AZdots = "plot palette: AZ.dots >> { A B C D E F G ... Z ]",
    digits  = "digits as character >> as.character(0:9)",
    az      = "letters",
    AZ      = "LETTERS",
    azAZ    = "lower + uppercase letters >> c(letters, LETTERS)",
    vowels  = "lower + uppercase vowels >> c('a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U')",
    files   = "valid chars for file names >> c(letters, LETTERS, 0:9, '(', ')', ' ', '_', '.', '-')",
    models  = "valid chars for model spec >> c(letters, LETTERS, 0:9, ' ', '_', '.', ':', '+', '*'. '~')",
    labels  = "valid chars for plotting labels >> c(letters, LETTERS, 0:9, '{', '[', '(', ')', ']', '}', ' ', '_', '.', '-')",
    names   = "valid chars for model element names >> c(letters, LETTERS, 0:9, '_' , '.')",
    right   = "valid chars for right-side model spec >> c(letters, LETTERS, 0:9, ' ', '_', '.', ':', '+', '*')",
    files0  = "valid chars for restricted file names >> c(letters, LETTERS, 0:9, ' ', '.')",
    names0  = "valid chars for restricted model element names >> c(letters, LETTERS, 0:9)",
    models0 = "valid chars for restricted model specification >> c(letters, LETTERS, 0:9, ' ', '+', '*', '~')",
    right0  = "valid chars for restricted right-side model spec >> c(letters, LETTERS, 0:9, ' ', '+', '*')" ,
    bbb = "basic property values >> bbb_props() >> AKA basic structural properties",
    ccc = "xclass property values >> ccc_props() >> AKA extended class properties",
    ddd = "defined-D property values >> ddd_props() >> AKA defined dimensionality properties",
    eee = "effective-D property values >> eee_props() >> AKA effective dimensionality properties",
    iii = "integrity property values >> iii_props() >> AKA degree of completeness and uniqueness properties",
    mmm = "xmode property values >> mmm_props() >> AKA extended mode properties",
    sss = "shape property values >> sss_props() >> AKA geometric shape properties",
    BBB = "uppercase basic property values >> toupper(bbb_props()) >> AKA uppercase basic structural properties",
    CCC = "uppercase xclass property values >> toupper(ccc_props()) >> AKA uppercase extended class properties",
    DDD = "uppercase defined-D property values >> toupper(ddd_props()) >> AKA uppercase defined dimensionality properties",
    EEE = "uppercase effective-D property values >> toupper(eee_props()) >> AKA uppercase effective dimensionality properties",
    III = "uppercase integrity property values >> toupper(iii_props()) >> AKA uppercase completeness and uniqueness properties",
    MMM = "uppercase xmode property values >> toupper(mmm_props()) >> AKA uppercase extended mode properties",
    SSS = "uppercase shape property values >> toupper(sss_props()) >> AKA uppercase geometric shape properties"
  )
  uj::add_at(out, descriptions = descriptions)
}

#' @rdname values
#' @export
value_names <- function() {uj::EN(uj::values())}

#' @rdname values
#' @export
value_table <- function() {
  x <- uj::values()
  values <- base::sapply(x, paste0, collapse = "|")
  uj::tb(name = uj::EN(x), value = values, description = uj::at(x, "descriptions"))
}

#' @rdname values
#' @export
value <- function(...) {
  x <- uj::asCHR(base::match.call())
  x <- x[2:uj::N(x)]
  uj::av(uj::values()[x])
}

#' @rdname values
#' @export
values <- values

#' @rdname values
#' @export
val_names <- value_names

#' @rdname values
#' @export
val_table <- value_table

#' @rdname values
#' @export
val <- value

#' @rdname values
#' @export
vs <- values

#' @rdname values
#' @export
vnames <- value_names

#' @rdname values
#' @export
vtable <- value_table

#' @rdname values
#' @export
v <- value
